language: node_js

node_js:
  - node

services:
  - postgresql

before_script:
  - psql -c 'create database testdms;' -U node -P node

after_script:
  - node node_modules/codeclimate-test-reporter/bin/codeclimate < coverage/lcov.info