language: node_js

node_js:
  - node

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

after_script:
  - node node_modules/codeclimate-test-reporter/bin/codeclimate < coverage/lcov.info